### ISSUE TITLE
EditPage: "task is done" should be "task is open"

### ISSUE THREAD

**Issue by jklingen** [Armadill0/harbour-tasklist#36]
The ```taskStatus``` TextSwitch uses ```taskOpenAppearance```, but is labeled "task is done".

My first idea was to invert the ```checked``` condition, but I think it is more intuitive for users to see the same checkstate as in the list view, so renaming the label is probably more user friendly.

Thanks for developing Tasklist, very handy :)

**Comment by jklingen** [comment]
Stumbled across this PR just now: https://github.com/Armadill0/harbour-tasklist/pull/1, which is part of the solution I had in mind *first*.

But I still think it should be fixed by changing the label. I agree that it is good to use the ```TextSwitch```es in a consistent manner, but in combination with the label it is a bit confusing.

**Comment by Armadill0** [comment]
Any idea for a better labeling? :smile:

**Comment by jklingen** [comment]
Well, on a second thought, my first suggestion ("task is open") would be equally broken when the user has the other configuration for the check state.

So, after a third thought, maybe the label would change depending on the config? I.e.
"Task is done" when configured to display done tasks as checked, and
"Task is open" when configured to display open tasks as checked.


That said, I'd also consider to replace this option with some other kind of state visualization, I assume the inverse-check-option will keep on complicating things like this in the future. Purists might argue that it is semantically incorrect to use a checked state that way.

**Comment by Armadill0** [comment]
How about something neutral like "task status"? I could also add a legend which explains which status means what, depending on what currently is configured.

But your third thought doesn't sound that bad. Although I'm thinking to change the label according to the tasks status. So if the task is open, the label is "task is open" independent if the checkbox is marked or not and vice versa with "task is done".

In general the inverse-check option isn't that complicated as it is handled by one function which has to be used to get the correct status. So I don't think it will complicate other things.

Another way of visualization could be a solution, but how do you want to do this? The current way is simple and easy to see for everyone. I already thought about something like it is done in the Jolla Notes app with colors but I'm not really convinced of this. Maybe I'll do some testing with this in the next weeks.

**Comment by jklingen** [comment]
Agreed, I saw the central implementation of the functionality... but it obviously still can't handle all situations, as we see in this thread ;-)

I really don't blame you for implementing it that way, not at all. One of the first things I did with the app was to configure it to behave like that, because I thought it was strange to have the items visually highlighted when they have been done. And just now, after thinking about the switch on the edit page, I realize that it is arguable to indicate undone items as "checked". Not so much from the visible UI perspective, but for a user of a screenreader it might be a little confusing to see all undone items checked, while the finished tasks are not (but well, they probably have chosen this option themselves).

That's why I suggested not to redefine the checked state, but change the appearance of checked items instead, to be highlighted when unchecked, and maybe when done display a checkmark image instead of the default silica TextSwitch dot. This might require a custom component, though.

But I don't want to get too picky here, just wanted to let you know about my thoughts. Feel free to choose what you consider appropriate :)
For now, it might be really enough to make the label change dynamically - your approach "task is open"/"task is closed" may still not be 100% semantically correct, but it is a clever idea, it adds consistency with the rest of the app.

Thanks for listening :)

**Comment by Armadill0** [comment]
I'm sorry. I didn' want to push your thoughts away! It's really helpful to have people discussing some features as I started developing TaskList only depending on my needs. This is also why we have this reversible check item for tasks. :grinning: 

With version 1.2.0 the task item also is a custom item. So it is much easier to change things concerning this. But my goal always was to keep TaskList as close to the normal Sailfish components as possible to give the user the feeling to be "at home". :wink: 
However I really see your issue and as already said I also thought about changing some things in the past.

Maybe I'll do some tests changing the task icons in the next days to the a checkbox. :smile:

**Comment by jklingen** [comment]
Don't worry, I never felt being wiped away :) As a user, I love sharing thoughts and ideas about my user experience. As a developer, I know that user suggestions sometimes just don't fit. ;-)

**Comment by jklingen** [comment]
FYI: I just noticed a related issue - when configuring the "unchecked" state for open tasks, together with strike-through for closed tasks, it results in the *open* tasks bein struck through instead. Not too severe, just a bit confusing at the first moment :)

**Comment by Armadill0** [comment]
Current task status is now clearly described by the text label.
