### ISSUE TITLE
Add tags to a task

### ISSUE THREAD

**Issue by mxwell** [Armadill0/harbour-tasklist#37]
Tags are helpful to filter tasks by some attribute, e.g. a location or a context. Each task could have many tags. New pages should be created (or existing ones should be modified) to support displaying of a list with tasks attributed by a specified tag.

**Comment by Armadill0** [comment]
Do you think it would be better to add a new table for the tags or should we add another field to the "tasks" table  where the tags are separated by a special char which is not allowed in the tag names?

I'm not sure what the best way (especially in terms of sqlite performance) would be.

The last case would need a database update. In the first case we can simply create the table with a new version of TaskList.

**Comment by mxwell** [comment]
Performance doesn't seem to be an issue for a typical use case, but a separate table is more natural in SQL for a 'many-to-many' association.

**Comment by Armadill0** [comment]
Ok, so no schema update necessary. :smile:

**Comment by Armadill0** [comment]
fixed by pull request #46
