### ISSUE TITLE
Forking and building doesn't succeed in the latest qtcreator by Jolla

### ISSUE THREAD

**Issue by Rikujolla** [Armadill0/harbour-tasklist#38]
I tried to get the code worl in the latest qtcreator to compile the code to my Jolla. The error message appeared as follows:

/home/riku/jolla/forks/harbour-tasklist/third_party/notifications.pri(1): error(message) requires one argument.

Compiler output is as follows:
16:56:01: Running steps for project harbour-tasklist...
16:56:01: Start SDK: Starting "MerSDK" virtual machine...
16:56:25: Starting: "/home/riku/.config/SailfishBeta2/mer-sdk-tools/MerSDK/SailfishOS-armv7hl/qmake" /home/riku/jolla/forks/harbour-tasklist/harbour-tasklist.pro -r -spec linux-g++
Info Changing to working dir: /home/mersdk/share//jolla/forks/harbour-tasklist/rpm
Warning GPLv3 related license might be unacceptable.
Warning NEW spec file created: harbour-tasklist.spec, maybe customized spec content is needed!

Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.2ZANbu
/home/mersdk/share/jolla/forks/harbour-tasklist/third_party/notifications.pri:1: error(message) requires one argument.
sh: line 0: cd: /home/mersdk/share/jolla/forks/harbour-tasklist/third_party/nemo-qml-plugin-notifications/src: No such file or directory
WARNING: Failure to find: ../harbour-tasklist/third_party/nemo-qml-plugin-notifications/src/notification.cpp
WARNING: Failure to find: ../harbour-tasklist/third_party/nemo-qml-plugin-notifications/src/notificationmanagerproxy.cpp
WARNING: Failure to find: ../harbour-tasklist/third_party/nemo-qml-plugin-notifications/src/notification.h
WARNING: Failure to find: ../harbour-tasklist/third_party/nemo-qml-plugin-notifications/src/notificationmanagerproxy.h
16:56:46: The process "/home/riku/.config/SailfishBeta2/mer-sdk-tools/MerSDK/SailfishOS-armv7hl/qmake" exited normally.
16:56:46: Starting: "/home/riku/.config/SailfishBeta2/mer-sdk-tools/MerSDK/SailfishOS-armv7hl/make" 
Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.GQ3m6r
g++ -c -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -fmessage-length=0 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -mno-thumb -Wno-psabi -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/share/qt5/mkspecs/linux-g++ -I../harbour-tasklist -I/home/mersdk/share/jolla/forks/harbour-tasklist/third_party/nemo-qml-plugin-notifications/src -I/usr/include/sailfishapp -I/usr/include/mdeclarativecache5 -I/usr/include/qt5 -I/usr/include/qt5/QtQuick -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtDBus -I/usr/include/qt5/QtQml -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I. -I. -o harbour-tasklist.o ../harbour-tasklist/src/harbour-tasklist.cpp
../harbour-tasklist/src/harbour-tasklist.cpp:35:26: fatal error: notification.h: No such file or directory
compilation terminated.
make: *** [harbour-tasklist.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.GQ3m6r (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.GQ3m6r (%build)
16:56:54: The process "/home/riku/.config/SailfishBeta2/mer-sdk-tools/MerSDK/SailfishOS-armv7hl/make" exited with code 1.
Error while building/deploying project harbour-tasklist (kit: MerSDK-SailfishOS-armv7hl)
When executing step 'Make'
16:56:54: Elapsed time: 00:53.

Qtcreator details are as follows:

Qt Creator 3.1.2
Based on Qt 5.2.1 (GCC 4.4.3, 32 bit)
Built on Feb 9 2015 at 11:00:14
From revision 672654b-jolla

**Comment by Armadill0** [comment]
use
```git submodule init
git submodule update```
to initialize the notifications submodule
