### ISSUE TITLE
Introduce new smart lists

### ISSUE THREAD

**Issue by mxwell** [Armadill0/harbour-tasklist#39]
1. Several new types of smart lists could be introduced:
    - `Today` - all tasks with a due date not exceeding today's date,
    - `Tomorrow` - all tasks that should be done til tomorrow,
    - `#tag` - all tasks with some specified tag, one can get there after tap in the list of all tags.
2. All kinds of lists (both smart and normal) should be sorted in the same way, so that a user could see tasks, that require more attention, on top:
    - firstly by a status, because closed tasks aren't that important and don't have to be shown on top;
    - secondly by a due date, because one need to see tasks with a past or approaching deadline on top,
    - and by a priority: the bigger a priority, the higher a task goes.
3. I doubt the need of the smart list `New`: why does a user want to know about creation dates after all?

P.S. I don't want to sound harsh, it is just some questions to discuss :smile:

**Comment by Armadill0** [comment]
2. Are you speaking of lists or tasks? You mixed up both terms a bit. :wink: It also seems to me, that this is not in the scope of smart lists itself. It's more likely a sorting issue. Let's discuss this in issue #27 . :smile: 

3. For example think of the planned synchonization features. If another user adds some things to your shopping list while you're already in the store, you can have a fast look what's new. :smile: 
Another example would be if you added a new task some hours ago, you have many lists and you've forgotten which list the task has been added to.

**Comment by mxwell** [comment]
1. I guess, it's ok.
2. Yes, I agree, a task order is a separate issue.
3. It seems reasonable.

**Comment by mxwell** [comment]
Question 4. Also the transition between TaskPage and ListPage seems a little unnatural. It would be better off to go from the ListPage **to the right (or forth)** to the TaskPage with some task list and to go from the TaskPage **to the left (or back)** to the ListPage.

**Comment by Armadill0** [comment]
Hm. The reason I did it this way is, that the task page is the main page of the app (first page after start, first page after coming back from cover, menus to get to settings and about page and so on) and the page where the most actions are taken place in the app. The list page is more like a sub page which is only used sometimes.

As you can see on the SailfishOS design guide (https://sailfishos.org/design/navigation/), sub pages are aligned on the right side. So swiping to the right from task to list page and swiping to the left to go back seems to be the normal Sailfish way.

All other applications work this way I think. The only thing we could discuss is, that the list page could be the main page of the app, but I don't see arguments for this at the moment.

**Comment by mxwell** [comment]
I think transitions between ListPage, TagPage and TaskPage could be done better, if we change hierarchy. They can go as ListPage -> TaskPage or ListPage -> TagPage -> TaskPage. And it doesn't mean that ListPage should be the first page. TaskPage with the default list could be shown at start, but ListPage should be located to the left.

**Comment by Armadill0** [comment]
fixed by pull request #46
