### ISSUE TITLE
possibility to 'uncheck all done' in tasklist

### ISSUE THREAD

**Issue by PawelSpoon** [Armadill0/harbour-tasklist#45]
i would like to use task list as 'reusable' checklist 
i.e. all items needed for canoeing trip
a pulley entry 'undone all' would be the solution for me

**Comment by PawelSpoon** [comment]
Thank You !!

**Comment by Armadill0** [comment]
No problem, it was simple to add. But you have to wait a bit for the next release, because I'm preparing for a major release with many changes which need some more polishing.
