### ISSUE TITLE
Sync with Dropbox

### ISSUE THREAD

**Issue by mxwell** [Armadill0/harbour-tasklist#50]
Like Import/Export, but storage is app's directory at Dropbox. A user is authenticated via browser once.

This could serve as a backup and a common place for one's tasks (with prospective access from web or desktop app).

Doable with https://github.com/lycis/QtDropbox. Development access to Dropbox Core API is limited by 100 users. Production status and approval by Dropbox is required for more users.

**Comment by Armadill0** [comment]
Not a bad idea.

But there is already a Dropbox client which someone who wants to use Dropbox would use to synchronize other content I think.
Does it really make sense to implement an own Dropbox client just for skipping the step to copy the backups to the Dropbox directory?

Just to clarify: As I'm not using Dropbox and I don't know the usage workflow with Sailbox this might not be a valid argumentation. :wink:

**Comment by mxwell** [comment]
About Sailbox: It is more like Dropbox web client, but with more manual work. I've checked out Sailbox today and counted six steps to perform a basic upload. And I couldn't replace the existing file easily (though delete&upload worked).

Why is it worth implementing?

1) It's true backup: copying from one file (SQLite DB) to another on the same storage is not a backup.
2) Export/import with this could be as easy as tap on 'Sync' and waiting for several seconds, instead of the current workflow, that requires some learning :smile: 
3) If Dropbox is the central place to store data, then they're accessible virtually from anywhere. I believe simple webapp could be built on top of it, so a user could manage his tasks on a bigger computer.

**Comment by Armadill0** [comment]
Hi Murat,

I'm currently using "harbourtasklist" as dropbox developer app. Which app names did you reserve in your account? If we could use"harbour-tasklist" or "tasklist" that would be great. :smile:

**Comment by mxwell** [comment]
Hi,

Yeah, I used name 'harbour-tasklist'. Now I changed its name, so hopefully it would be available for you. And name 'tasklist' was taken before my tests.

**Comment by Armadill0** [comment]
It worked, thanks! :smile:

**Comment by mxwell** [comment]
I tried to sync, but couldn't. After logging out I synced with Dropbox, but into the different folder. Have you changed something recently?

**Comment by Armadill0** [comment]
Hm no, there have been no changes. The folder should be named "harbour-tasklist".

**Comment by mxwell** [comment]
I suspect the problem caused by cookies/cached data of web view. I've removed them, but my build doesn't have proper credentials for Dropbox. So I have to wait for your next release to test :sweat_smile:

**Comment by Armadill0** [comment]
I'll build 1.8.10 today. :smile:

**Comment by Armadill0** [comment]
There you go: https://github.com/Armadill0/harbour-tasklist/releases/tag/1.8.10 :smile: 

Just tested Dropbox and works normal for me.

**Comment by mxwell** [comment]
Tried another account too, but the file still goes into 'Apps/TaskList'.

Please, check this on your setup: sync with Dropbox and check that file goes into 'Apps/harbour-tasklist' by its timestamp. It should say something like 'N seconds ago'.

**Comment by Armadill0** [comment]
Hm... I recently tested after upgrading to SDK 1510. I entered credentials, was asked to activate the app for "harbour-tasklist" folder and received the list I uploaded yesterday from my mobile. So everything seems to work for me. :worried:
