### ISSUE TITLE
support for recuring tasks

### ISSUE THREAD

**Issue by Armadill0** [Armadill0/harbour-tasklist#53]
Recuring tasks have been requested through harbour comments.

Not sure what should be happen after the time period has been passed. Most logic effect would be to reactivate the task. This would need some sort of Timer which checks such tasks in a specific period of time e.g. hourly.

I don't know if this should really be in the scope of TaskList or if users should do such things with recuring calendar events.
Feel free to discuss the pros and cons. :smile:

**Comment by mxwell** [comment]
I think this could be implemented in TaskList too, because a calendar and a todo-list are different representations of the same entity (something like "planned future").

The feature could be seen just as a task, that after being closed transforms immediately into an open task with an updated due date. Because it's OK to have tasks with a due date in far future.

I also doubt the necessity to support so short recurrences, like hourly. Daily and more is OK. If one deals with intervals less than day, then he probably should use alarms :smile:

**Comment by Armadill0** [comment]
Hm yes, reactivating the task immediately after it has been done and set a new due date is a good solution.

What I'm a bit concerned about, is the new due date...
Should it be set to exactly the old due date  and be increased by the recurrence time period? Seems to be the best and simplest solution to me, but it could cause some annoyance if somebody has a daily recurring task and forgets some days to mark the task as done. But this could be solved by the user if he sets the due date manually to some date in the future.

Or should the base date been taken from the date when the task has been marked as done. This would solve the problem for the daily issue, but could cause issues with larger recurrence periods, that if the user marks the task a day later as done, the new due date is set also a day later than normal. And if the user recognizes this after some periods, he wants to correct this he also has to set the new due date manually.

Or we do both and decide depending on different time periods what should be done exactly. But this could cause some confusion at the user, because different time periods have a different behaviour.

After writing this, for me the first solution sounds the best, as I'm a friend of simple and comprehensible workflows. :smile: What do you think?

The hourly thing was meant in another context. Simply forget what I said about this. :wink: 

Brain dump: When implementing we mustn't forget to check if a due date is set before using the recurrence period and marking the task as undone. Maybe we could display a notification about this.

**Comment by mxwell** [comment]
I like this approach: https://www.rememberthemilk.com/help/?ctx=basics.basics.repeatformat

So repetition details could be crammed into a single string field in DB, but presence of "due date" should be forced, because it is required to determine the current point in the series.

**Comment by Armadill0** [comment]
Resolved with #59
