### ISSUE TITLE
Extend EditPage to use for adding new tasks with details

### ISSUE THREAD

**Issue by Armadill0** [Armadill0/harbour-tasklist#55]
Extend the already existing EditPage with the possibility to add new tasks directly with details like notes and so on to the database.

Differentiation could be done by the given or not given listid.

**Comment by mxwell** [comment]
What is the entry point for EditPage?

I have the following idea: a user entered a name, the name appeared in the list (at the top) with something like Remorse, that blinks and suggests to `Tap to add details`.

Another solution might be [Smart add](https://www.rememberthemilk.com/help/?ctx=basics.smartadd.whatis): it is a special syntax to enter details into a single text field, though it feels quite naturally. Google Calendar also has something like it. Obviously it would take some time to implement :smile:

**Comment by Armadill0** [comment]
EditPage is currently triggered by the ContextMenu of each task on the TaskPage. The decision if the page is in "edit" or "add" mode is pretty easy. I already did it with another app: https://github.com/Armadill0/harbour-phototools/blob/master/qml/pages/CameraEditPage.qml#L87

The reversed remorse action sounds interesting. Although I see a problem with the focus of the textfield, but this can be tested easily.

The Smart-add feature also looks very nice. As you already said it would take some time to implement. This should be done in a separate issue if somebody likes this feature. It also highly depends on the translations, which could be an issue when releasing the feature.

**Comment by mxwell** [comment]
If we choose the blinking as a way to go, then we need to communicate it to a user. E.g. when a user creates her first task, the app extends blinking period and shows small notification like "Tap blinking task to add more details".

**Comment by Armadill0** [comment]
True. I already thought about a first usage wizard, which is alread used from Jolla's apps and some other Sailfish apps I use. But I had no time to get deeper into it till now.

**Comment by Armadill0** [comment]
I just played around with the TouchInteractionHint, TapInteractionHint and InteractionHintLabel to evaluate if those could be used for a "first use tutorial" for new users.
To show something like the blinking edit possibility to the user it seems to be not that easy to setup a guide with those elements, because you would also need an automatic addition of a task and it's deletion afterwards if we want to start with a clean database.

It seems it's much more work to built a well designed Tutorial than I expected. :confused:

**Comment by Armadill0** [comment]
Another solution could be to add a Help-Page where the features, especially the hidden features of TaskList are explained. I already thought about something like that in the past.
It seems it's time to do it now. :smile:
