### ISSUE TITLE
Missing cover actions

### ISSUE THREAD

**Issue by smyru** [Armadill0/harbour-tasklist#62]
It seems to me that after some time cover actions disappear from a running application. This also happens when I accidentally start another instance of Tasklist. The latter cover is action less. I'm not sure whether this is an application or OS issue. 
![20150720210657](https://cloud.githubusercontent.com/assets/554271/8784822/0e048e3e-2f24-11e5-9f97-38e5d9966180.png)
![20150712134137](https://cloud.githubusercontent.com/assets/554271/8784823/0e04f7c0-2f24-11e5-8f58-2012b56134e2.png)

**Comment by Armadill0** [comment]
Hm, I never had such an issue although I'm using TaskList quite excessive. But to be honest I also don't know a way to start a second instance of an app.

I'll have a look in the code the next days. But I don't remember a code snippet which could hide all cover actions.

So in total this seems more like a SailfishOS bug or something like that to me.

**Comment by smyru** [comment]
Just to clarify, I am able to start various apps duped not just TaskList. Restarting the app usually restores  cover actions.

**Comment by Armadill0** [comment]
Well I think opening multiple instances of an application is not an official way to use them.

I'm also not able to reproduce the missing cover actions.

You should open a question at together.jolla.com to solve this issue. They might have more knowledge about this. :wink:

**Comment by smyru** [comment]
Well, I do not opt nor want to open many instances of the same app. I am actually surprised this is even possible.

**Comment by Armadill0** [comment]
Especially in this case you should ask at together.jolla.com. Maybe this really is a general issue with SailfishOS.

**Comment by smyru** [comment]
After upgrading to 1.1.7.28 cover actions are gone for good in Tasklist here. Have you observed this?

**Comment by Armadill0** [comment]
You mean cover actions are now completely gone? :fearful: 

That would really surprise me as we recently fixed a small bug regarding the list of list in the cover: https://github.com/Armadill0/harbour-tasklist/commit/8b1282cf5a167de971d1c4f182532223bf18a394
