### ISSUE TITLE
Support todo.txt format and allow webdav sync

### ISSUE THREAD

**Issue by tigre-bleu** [Armadill0/harbour-tasklist#81]
I like the gui of the app as it is, but in my use case I would want to share my tasklists with other people.

For that what could be a smart option is that:
- harbour-tasklist supports todo.txt format
- harbour-tasklist supports webdav to sync with owncloud

More info: https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format

**Comment by Armadill0** [comment]
Hi,

we already have some issues handling your requests. Have a look at #10 for the todo.txt support.

 The Owncloud sync is discussed in #2, but via caldav protocol instead of webdav. Feel free to join the discussions. :smile:
