### ISSUE TITLE
Warehouse  release

### ISSUE THREAD

**Issue by lewadedun** [Armadill0/harbour-tasklist#83]
You can put the program on openrepos.net?
I changed the phone to OnePlus X and I have no Jolla Store....

**Comment by Armadill0** [comment]
This question has already been asked in the past. Maybe I'll have a look at this, butno promises at this point.

In the meantime you can use the releases which I maintain at Github: https://github.com/Armadill0/harbour-tasklist/releases

**Comment by Armadill0** [comment]
Done: https://openrepos.net/content/armadillo/tasklist
